name: C/C++ CI

on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:    
      - master         # Push events on master branch
      - ilya1725-Encircular-cleanup

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    #- name: configure
    #  run: ./configure
    - name: make All doodles
      working-directory: ./doodles
      run: make all
    - name: Encircular
      working-directory: ./Encircular
      run: make encircular && make test
      
