name: C/C++ CI

on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:    
      - master         # Push events on master branch
      - '*'            # Matches all branch and tag names that don't contain a slash (/). 

jobs:
  build_doodles:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    #- name: configure
    #  run: ./configure
    - name: make All doodles
      working-directory: ./doodles
      run: make all
      
  build_encircular:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    #- name: configure
    #  run: ./configure
    - name: Build Encircular
      working-directory: ./Encircular
      run: make encircular && make test
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test Encircular
      working-directory: ./Encircular
      run: make test
